services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=CouponSystem'
      - 'MYSQL_PASSWORD=1234'
      - 'MYSQL_ROOT_PASSWORD=1234'
      - 'MYSQL_USER=root'
    ports:
      - '3306:3306'

#  redis:
#    image: 'redis:latest'
#    ports:
#      - '6379'
