version: '3.8'  # Docker Compose 파일 버전

services:
  # Zookeeper 서비스 설정
  zookeeper-1:
    image: confluentinc/cp-zookeeper:5.5.1  # Zookeeper 이미지
    ports:
      - '32181:32181'  # Zookeeper 클라이언트 포트 매핑
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181  # Zookeeper가 클라이언트 요청을 수신하는 포트
      ZOOKEEPER_TICK_TIME: 2000  # Zookeeper heartbeat 간격(ms)

  # Kafka 브로커 1 설정
  kafka-1:
    image: confluentinc/cp-kafka:5.5.1  # Kafka 이미지
    ports:
      - '9092:9092'  # Kafka 브로커 1의 외부 포트 매핑
    depends_on:
      - zookeeper-1  # Zookeeper 의존성 설정
    environment:
      KAFKA_BROKER_ID: 1  # 브로커 ID, 클러스터 내에서 고유해야 함
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:32181  # Zookeeper 연결 정보
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      # 리스너 프로토콜 매핑: 내부 및 외부 클라이언트를 위한 설정
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      # 브로커 간 통신에 사용하는 리스너 이름
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:29092,EXTERNAL://localhost:9092
      # 클라이언트가 접근할 브로커 주소 설정
      KAFKA_MIN_INSYNC_REPLICAS: 2  # 최소 동기화 복제본 수 설정

  # Kafka 브로커 2 설정
  kafka-2:
    image: confluentinc/cp-kafka:5.5.1  # Kafka 이미지
    ports:
      - '9093:9093'  # Kafka 브로커 2의 외부 포트 매핑
    depends_on:
      - zookeeper-1  # Zookeeper 의존성 설정
    environment:
      KAFKA_BROKER_ID: 2  # 브로커 ID, 클러스터 내에서 고유해야 함
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:32181  # Zookeeper 연결 정보
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      # 리스너 프로토콜 매핑: 내부 및 외부 클라이언트를 위한 설정
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      # 브로커 간 통신에 사용하는 리스너 이름
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:29093,EXTERNAL://localhost:9093
      # 클라이언트가 접근할 브로커 주소 설정
      KAFKA_MIN_INSYNC_REPLICAS: 2  # 최소 동기화 복제본 수 설정

  # Kafka 브로커 3 설정
  kafka-3:
    image: confluentinc/cp-kafka:5.5.1  # Kafka 이미지
    ports:
      - '9094:9094'  # Kafka 브로커 3의 외부 포트 매핑
    depends_on:
      - zookeeper-1  # Zookeeper 의존성 설정
    environment:
      KAFKA_BROKER_ID: 3  # 브로커 ID, 클러스터 내에서 고유해야 함
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:32181  # Zookeeper 연결 정보
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      # 리스너 프로토콜 매핑: 내부 및 외부 클라이언트를 위한 설정
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      # 브로커 간 통신에 사용하는 리스너 이름
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:29094,EXTERNAL://localhost:9094
      # 클라이언트가 접근할 브로커 주소 설정
      KAFKA_MIN_INSYNC_REPLICAS: 2  # 최소 동기화 복제본 수 설정
