server:
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CouponSystem?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        use_sql_comments: true
        format_sql: true
    #        show_sql: true 이거 키면 SQL 두번 나옴
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always


# Prometheus와 Grafana를 사용한 Spring Boot 애플리케이션 모니터링 설정
management:
#  server: 내부망에서만 접근 설정
#    port: 
  endpoints:
    web:
      exposure:
        include: "*" # 모든 Actuator 엔드포인트를 노출
#        include: prometheus # 모든 Actuator 엔드포인트를 노출
  endpoint:
    prometheus:
      access: unrestricted # Prometheus 메트릭 엔드포인트에 접근 허용 (기본값)
  prometheus:
    metrics:
      export:
        enabled: true # Prometheus 메트릭 수출을 활성화

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.example.file_test: debug

springdoc:
  # Swagger에서 문서화할 패키지 설정
  packages-to-scan: com.gio.couponsystem

  # 기본 소비 미디어 타입 설정 (요청 데이터 타입)
  default-consumes-media-type: application/json;charset=UTF-8 # UTF-8로 JSON 데이터 인코딩

  # 기본 생성 미디어 타입 설정 (응답 데이터 타입)
  default-produces-media-type: application/json;charset=UTF-8 # UTF-8로 JSON 데이터 인코딩

  # OpenAPI 문서 경로 및 그룹화 설정
  api-docs:
    path: /api # OpenAPI 문서를 제공할 기본 경로 (예: /api 또는 /v3/api-docs)
  #    groups:
  #      enabled: true # 그룹화 기능 활성화
  #      group-configs:
  #        - group: coupons # 쿠폰 관련 API 그룹
  #          paths-to-match: /coupons/** # 쿠폰 관련 API 경로를 문서화
  #        - group: users # 사용자 관련 API 그룹
  #          paths-to-match: /users/** # 사용자 관련 API 경로를 문서화

  # Swagger 캐시 설정
  cache:
    disabled: true # 캐싱 비활성화 (개발 중 문서 변경 시 즉시 반영)

  # Swagger UI 설정
  swagger-ui:
    path: /ui # Swagger UI에 접근할 경로 (기본값: /swagger-ui.html)
    operations-sorter: method # API 문서를 HTTP 메서드(GET, POST 등) 순으로 정렬
    display-request-duration: true # 요청의 처리 시간을 UI에서 표시
    persist-authorization: true # 인증 정보를 유지하도록 설정
    deep-linking: true # URL 경로를 통한 API 문서 바로가기 활성화
    doc-expansion: list # 기본 문서 열람 방식: 리스트 형태 (또는 none, full 가능)
